import type { ScoreReport } from "../core/scoring.js";
import type { ScoreAdjustment } from "../agents/contracts/tuning-agent.js";
import type { MismatchCase } from "../agents/contracts/evaluation-agent.js";

export interface CalibrationNodeVisual {
  nodeId: string;
  nodePath: string;
  figmaScreenshotBase64: string;
  renderedScreenshotBase64: string;
  difficulty: string;
  issues: Array<{ ruleId: string; severity: string; message: string; why: string; fix: string }>;
}

export interface CalibrationHtmlReportData {
  fileName: string;
  fileKey: string;
  analyzedAt: string;
  scoreReport: ScoreReport;
  nodeVisuals: CalibrationNodeVisual[];
  adjustments: ScoreAdjustment[];
  mismatches: MismatchCase[];
  validatedRules: string[];
}

export function generateCalibrationHtmlReport(data: CalibrationHtmlReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Calibration Report - ${esc(data.fileName)}</title>
  <style>${getStyles()}</style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Calibration Report</h1>
      <p class="file-name">${esc(data.fileName)}</p>
      <p class="meta">Analyzed: ${esc(data.analyzedAt)} | Grade: ${data.scoreReport.overall.grade} (${data.scoreReport.overall.percentage}%)</p>
    </header>

    <section class="score-card">
      <div class="grade grade-${data.scoreReport.overall.grade}">${data.scoreReport.overall.grade}</div>
      <div class="score-info">
        <div class="score-pct">${data.scoreReport.overall.percentage}%</div>
        <div class="score-label">Overall Score</div>
      </div>
    </section>

    <section>
      <h2>Category Scores</h2>
      <div class="cat-grid">
${Object.entries(data.scoreReport.byCategory).map(([cat, s]) => `        <div class="cat-card">
          <div class="cat-name">${esc(cat)}</div>
          <div class="cat-score" style="color:${s.percentage >= 80 ? "#16a34a" : s.percentage >= 60 ? "#ca8a04" : "#dc2626"}">${s.percentage}%</div>
          <div class="cat-issues">${s.issueCount} issues</div>
        </div>`).join("\n")}
      </div>
    </section>

${data.nodeVisuals.length > 0 ? renderNodeVisuals(data.nodeVisuals, data.fileKey) : ""}

${data.adjustments.length > 0 ? renderAdjustments(data.adjustments) : ""}

    <footer>
      <p>Generated by <strong>Design Readiness Checker</strong> — Calibration Pipeline</p>
    </footer>
  </div>
</body>
</html>`;
}

function renderNodeVisuals(nodes: CalibrationNodeVisual[], fileKey: string): string {
  const cards = nodes.map((n) => {
    const diffClass = n.difficulty === "easy" ? "diff-easy"
      : n.difficulty === "moderate" ? "diff-moderate"
      : "diff-hard";

    const issueList = n.issues.map((i) => `
            <li class="cal-issue">
              <span class="severity-badge badge-${i.severity}">${esc(i.severity)}</span>
              <span class="cal-issue-msg">${esc(i.message)}</span>
              <div class="cal-issue-detail"><strong>Why:</strong> ${esc(i.why)}</div>
              <div class="cal-issue-detail"><strong>Fix:</strong> ${esc(i.fix)}</div>
            </li>`).join("\n");

    const figmaLink = `https://www.figma.com/design/${fileKey}?node-id=${encodeURIComponent(n.nodeId)}`;

    return `
    <div class="node-card">
      <div class="node-header">
        <h3>${esc(n.nodePath)}</h3>
        <span class="diff-badge ${diffClass}">${esc(n.difficulty)}</span>
      </div>
      <div class="compare-grid">
        <div class="compare-box">
          <div class="compare-label">Figma Original</div>
          <a href="${figmaLink}" target="_blank" rel="noopener">
            <img src="data:image/png;base64,${n.figmaScreenshotBase64}" alt="Figma">
          </a>
        </div>
        <div class="compare-box">
          <div class="compare-label">Claude Implementation</div>
          <img src="data:image/png;base64,${n.renderedScreenshotBase64}" alt="Rendered">
        </div>
      </div>
      ${n.issues.length > 0 ? `<ul class="cal-issue-list">${issueList}\n          </ul>` : ""}
    </div>`;
  });

  return `
    <section>
      <h2>Node Comparison (${nodes.length})</h2>
      ${cards.join("\n")}
    </section>`;
}

function renderAdjustments(adjustments: ScoreAdjustment[]): string {
  const rows = adjustments.map((a) => {
    const severityChange = a.proposedSeverity
      ? `${esc(a.currentSeverity)} → ${esc(a.proposedSeverity)}`
      : esc(a.currentSeverity);
    return `        <tr>
          <td><code>${esc(a.ruleId)}</code></td>
          <td>${a.currentScore}</td>
          <td><strong>${a.proposedScore}</strong></td>
          <td>${severityChange}</td>
          <td>${esc(a.confidence)}</td>
          <td>${esc(a.reasoning)}</td>
        </tr>`;
  });

  return `
    <section>
      <h2>Score Adjustments (${adjustments.length})</h2>
      <table class="adj-table">
        <thead>
          <tr><th>Rule</th><th>Current</th><th>Proposed</th><th>Severity</th><th>Confidence</th><th>Reasoning</th></tr>
        </thead>
        <tbody>
${rows.join("\n")}
        </tbody>
      </table>
    </section>`;
}

function getStyles(): string {
  return `
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; line-height:1.6; color:#1a1a1a; background:#f5f5f5; }
    .container { max-width:1200px; margin:0 auto; padding:2rem; }
    header { text-align:center; margin-bottom:2rem; }
    header h1 { font-size:2rem; margin-bottom:.5rem; }
    .file-name { font-size:1.25rem; color:#666; }
    .meta { font-size:.875rem; color:#999; margin-top:.5rem; }
    section { background:#fff; border-radius:12px; padding:1.5rem; margin-bottom:1.5rem; box-shadow:0 1px 3px rgba(0,0,0,.1); }
    h2 { font-size:1.25rem; margin-bottom:1rem; color:#333; }

    .score-card { display:flex; align-items:center; justify-content:center; gap:2rem; }
    .grade { width:100px; height:100px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:2.5rem; font-weight:bold; color:#fff; }
    .grade-A { background:linear-gradient(135deg,#10b981,#059669); }
    .grade-B { background:linear-gradient(135deg,#3b82f6,#2563eb); }
    .grade-C { background:linear-gradient(135deg,#f59e0b,#d97706); }
    .grade-D { background:linear-gradient(135deg,#f97316,#ea580c); }
    .grade-F { background:linear-gradient(135deg,#ef4444,#dc2626); }
    .score-pct { font-size:2.5rem; font-weight:bold; }
    .score-label { color:#666; }

    .cat-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:1rem; }
    .cat-card { padding:1rem; border-radius:8px; background:#f9fafb; border:1px solid #e5e7eb; text-align:center; }
    .cat-name { font-size:.8rem; color:#666; margin-bottom:.25rem; }
    .cat-score { font-size:1.5rem; font-weight:bold; }
    .cat-issues { font-size:.75rem; color:#999; }

    .node-card { border:1px solid #e5e7eb; border-radius:8px; padding:1rem; margin-bottom:1rem; background:#fafafa; }
    .node-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:.75rem; }
    .node-header h3 { font-size:.95rem; color:#333; }
    .diff-badge { padding:.2rem .5rem; border-radius:4px; font-size:.75rem; font-weight:600; }
    .diff-easy { background:#dcfce7; color:#16a34a; }
    .diff-moderate { background:#fef9c3; color:#ca8a04; }
    .diff-hard { background:#fee2e2; color:#dc2626; }

    .compare-grid { display:grid; grid-template-columns:1fr 1fr; gap:1rem; margin-bottom:.75rem; }
    .compare-box { text-align:center; }
    .compare-box img { width:100%; border:1px solid #e5e7eb; border-radius:4px; }
    .compare-label { font-size:.75rem; color:#666; font-weight:600; margin-bottom:.5rem; }

    .cal-issue-list { list-style:none; }
    .cal-issue { padding:.5rem; border:1px solid #e5e7eb; border-radius:6px; margin-bottom:.5rem; background:#fff; }
    .cal-issue-msg { font-weight:500; font-size:.875rem; }
    .cal-issue-detail { font-size:.8rem; color:#666; margin-top:.25rem; }

    .severity-badge { padding:.15rem .4rem; border-radius:4px; font-size:.7rem; font-weight:600; text-transform:uppercase; margin-right:.5rem; }
    .badge-blocking { background:#fee2e2; color:#dc2626; }
    .badge-risk { background:#ffedd5; color:#ea580c; }
    .badge-missing-info { background:#fef9c3; color:#ca8a04; }
    .badge-suggestion { background:#dcfce7; color:#16a34a; }

    .adj-table { width:100%; border-collapse:collapse; font-size:.875rem; }
    .adj-table th,.adj-table td { padding:.5rem .75rem; border:1px solid #e5e7eb; text-align:left; }
    .adj-table th { background:#f9fafb; font-weight:600; }
    .adj-table code { background:#f3f4f6; padding:.1rem .3rem; border-radius:3px; font-size:.8rem; }

    footer { text-align:center; padding:2rem; color:#999; font-size:.875rem; }

    @media (max-width:768px) {
      .container { padding:1rem; }
      .compare-grid { grid-template-columns:1fr; }
      .score-card { flex-direction:column; gap:1rem; }
    }
  `;
}

function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
