/**
 * Pure template functions for report HTML rendering.
 * No Node.js dependencies — usable in browser via CanICode.* globals.
 *
 * Single source of truth for all report UI:
 * - CLI: generateHtmlReport() wraps with <html> shell
 * - Web app: CanICode.renderReportBody() → innerHTML
 * - Figma plugin: CanICode.renderReportBody() → innerHTML
 */

import type { Category } from "../contracts/category.js";
import type { Severity } from "../contracts/severity.js";
import type { AnalysisIssue } from "../engine/rule-engine.js";
import type { ScoreReport } from "../engine/scoring.js";
import { buildFigmaDeepLink } from "../adapters/figma-url-parser.js";
import {
  CATEGORIES,
  CATEGORY_LABELS,
  SEVERITY_LABELS,
  CATEGORY_DESCRIPTIONS,
  SEVERITY_ORDER,
} from "../ui-constants.js";
import {
  escapeHtml,
  severityDot,
  severityBadge,
  scoreBadgeStyle,
  renderGaugeSvg,
} from "../ui-helpers.js";

// ---- Data interface ----

export interface ReportData {
  fileName: string;
  fileKey: string;
  scores: ScoreReport;
  issues: AnalysisIssue[];
  nodeCount: number;
  maxDepth: number;
  figmaToken?: string;
}

// ---- Main render ----

/**
 * Render the report body content (everything inside <main>).
 * Does NOT include <html>, <head>, <body> — caller wraps as needed.
 */
export function renderReportBody(data: ReportData): string {
  const { scores, issues, fileKey, figmaToken } = data;
  const quickWins = getQuickWins(issues, 5);
  const issuesByCategory = groupIssuesByCategory(issues);

  return `
    <!-- Overall Score -->
    <section class="flex flex-col items-center pt-12 pb-6">
      ${renderGaugeSvg(scores.overall.percentage, 200, 10, scores.overall.grade)}
      <div class="mt-3 text-center">
        <span class="text-lg font-semibold">${scores.overall.percentage}</span>
        <span class="text-muted-foreground text-sm ml-1">/ 100</span>
      </div>
      <p class="text-muted-foreground text-sm mt-1">Overall Score</p>
    </section>

    <!-- Category Gauges -->
    <section class="bg-card border border-border rounded-lg shadow-sm p-6 mb-6">
      <div class="grid grid-cols-3 sm:grid-cols-6 gap-4">
${CATEGORIES.map(cat => {
    const cs = scores.byCategory[cat];
    const desc = CATEGORY_DESCRIPTIONS[cat];
    return `        <a href="#cat-${cat}" class="flex flex-col items-center group relative cursor-pointer no-underline text-foreground hover:opacity-80 transition-opacity">
          ${renderGaugeSvg(cs.percentage, 100, 7)}
          <span class="text-xs font-medium mt-2.5 text-center leading-tight">${CATEGORY_LABELS[cat]}</span>
          <span class="text-[11px] text-muted-foreground">${cs.issueCount} issues</span>
          <div class="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 hidden group-hover:block bg-zinc-900 text-white text-xs px-3 py-2 rounded-md max-w-[220px] w-max z-10 shadow-lg pointer-events-none">
            ${esc(desc)}
            <div class="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-zinc-900"></div>
          </div>
        </a>`;
  }).join("\n")}
      </div>
    </section>

    <!-- Issue Summary -->
    <section class="bg-card border border-border rounded-lg shadow-sm p-4 mb-6">
      <div class="flex flex-wrap items-center justify-center gap-6">
        ${renderSummaryDot("bg-red-500", scores.summary.blocking, "Blocking")}
        ${renderSummaryDot("bg-amber-500", scores.summary.risk, "Risk")}
        ${renderSummaryDot("bg-zinc-400", scores.summary.missingInfo, "Missing Info")}
        ${renderSummaryDot("bg-green-500", scores.summary.suggestion, "Suggestion")}
        <div class="border-l border-border pl-6 flex items-center gap-2">
          <span class="text-xl font-bold tracking-tight">${scores.summary.totalIssues}</span>
          <span class="text-sm text-muted-foreground">Total</span>
        </div>
      </div>
    </section>

${quickWins.length > 0 ? renderOpportunities(quickWins, fileKey) : ""}

    <!-- Categories -->
    <div class="space-y-3">
${CATEGORIES.map(cat => renderCategory(cat, scores, issuesByCategory.get(cat) ?? [], fileKey, figmaToken)).join("\n")}
    </div>

    <!-- Footer -->
    <footer class="mt-12 pt-6 border-t border-border text-center">
      <p class="text-sm text-muted-foreground">Generated by <span class="font-semibold text-foreground">CanICode</span></p>
      <p class="text-xs text-muted-foreground/60 mt-1">${new Date().toLocaleString()} · ${data.nodeCount} nodes · Max depth ${data.maxDepth}</p>
    </footer>`;
}

// ---- Components ----

const SEVERITY_TOOLTIPS: Record<string, string> = {
  Blocking: "Cannot implement correctly without fixing. Direct impact on screen reproduction.",
  Risk: "Implementable now but will break or increase cost later.",
  "Missing Info": "Information is absent, forcing AI to guess.",
  Suggestion: "Not immediately problematic, but improves systemization.",
};

export function renderSummaryDot(dotClass: string, count: number, label: string): string {
  const tooltip = SEVERITY_TOOLTIPS[label] ?? "";
  return `<div class="flex items-center gap-2 relative group cursor-help" title="${esc(tooltip)}">
          <span class="w-2.5 h-2.5 rounded-full ${dotClass}"></span>
          <span class="text-lg font-bold tracking-tight">${count}</span>
          <span class="text-sm text-muted-foreground">${label}</span>
          <div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block bg-zinc-900 text-white text-xs px-3 py-2 rounded-md max-w-[220px] w-max z-10 shadow-lg pointer-events-none">${esc(tooltip)}<div class="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-zinc-900"></div></div>
        </div>`;
}

export function renderOpportunities(issues: AnalysisIssue[], fileKey: string): string {
  const maxAbs = issues.reduce((m, i) => Math.max(m, Math.abs(i.calculatedScore)), 1);
  return `
    <!-- Opportunities -->
    <section class="bg-card border border-border rounded-lg shadow-sm mb-6 overflow-hidden">
      <div class="px-6 py-4 border-b border-border">
        <h2 class="text-sm font-semibold flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-red-500"></span>
          Opportunities
        </h2>
        <p class="text-xs text-muted-foreground mt-1">Top blocking issues — fix these first for the biggest improvement.</p>
      </div>
      <div class="divide-y divide-border">
${issues.map(issue => {
    const def = issue.rule.definition;
    const link = buildFigmaDeepLink(fileKey, issue.violation.nodeId);
    const barW = Math.round((Math.abs(issue.calculatedScore) / maxAbs) * 100);
    return `        <div class="px-6 py-3 flex items-center gap-4 hover:bg-muted/50 transition-colors">
          <div class="flex-1 min-w-0">
            <div class="text-sm font-medium truncate">${esc(def.name)}</div>
            <div class="text-xs text-muted-foreground truncate mt-0.5">${esc(issue.violation.message)}</div>
          </div>
          <div class="w-32 flex items-center gap-2 shrink-0">
            <div class="flex-1 h-1.5 bg-muted rounded-full overflow-hidden">
              <div class="h-full bg-red-500 rounded-full" style="width:${barW}%"></div>
            </div>
            <span class="text-xs font-medium text-red-600 w-12 text-right">${issue.calculatedScore}</span>
          </div>
          <a href="${link}" target="_blank" rel="noopener" class="text-xs text-muted-foreground hover:text-foreground shrink-0 no-print">Figma →</a>
        </div>`;
  }).join("\n")}
      </div>
    </section>`;
}

export function renderCategory(
  cat: Category,
  scores: ScoreReport,
  issues: AnalysisIssue[],
  fileKey: string,
  figmaToken?: string
): string {
  const cs = scores.byCategory[cat];
  const hasProblems = issues.some(i => i.config.severity === "blocking" || i.config.severity === "risk");

  const bySeverity = new Map<Severity, AnalysisIssue[]>();
  for (const sev of SEVERITY_ORDER) bySeverity.set(sev, []);
  for (const issue of issues) bySeverity.get(issue.config.severity)?.push(issue);

  return `
      <details id="cat-${cat}" class="bg-card border border-border rounded-lg shadow-sm overflow-hidden group"${hasProblems ? " open" : ""}>
        <summary class="px-5 py-3.5 flex items-center gap-3 cursor-pointer hover:bg-muted/50 transition-colors select-none">
          <span class="inline-flex items-center justify-center w-10 h-6 rounded-md text-xs font-bold border ${scoreBadgeStyle(cs.percentage)}">${cs.percentage}</span>
          <div class="flex-1 min-w-0">
            <div class="text-sm font-semibold">${CATEGORY_LABELS[cat]}</div>
            <div class="text-xs text-muted-foreground">${esc(CATEGORY_DESCRIPTIONS[cat])}</div>
          </div>
          <span class="text-xs text-muted-foreground">${cs.issueCount} issues</span>
          <svg class="w-4 h-4 text-muted-foreground transition-transform group-open:rotate-180 shrink-0 no-print" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path d="M19 9l-7 7-7-7"/></svg>
        </summary>
        <div class="border-t border-border">
${issues.length === 0
    ? '          <div class="px-5 py-4 text-sm text-green-600 font-medium">No issues found</div>'
    : SEVERITY_ORDER
        .filter(sev => (bySeverity.get(sev)?.length ?? 0) > 0)
        .map(sev => renderSeverityGroup(sev, bySeverity.get(sev) ?? [], fileKey, figmaToken))
        .join("\n")
}
        </div>
      </details>`;
}

export function renderSeverityGroup(
  sev: Severity,
  issues: AnalysisIssue[],
  fileKey: string,
  figmaToken?: string
): string {
  return `          <div class="px-5 py-3">
            <div class="flex items-center gap-2 mb-2">
              <span class="w-2 h-2 rounded-full ${severityDot(sev)}"></span>
              <span class="text-xs font-semibold uppercase tracking-wider">${SEVERITY_LABELS[sev]}</span>
              <span class="text-xs text-muted-foreground ml-auto">${issues.length}</span>
            </div>
            <div class="space-y-1">
${issues.map(issue => renderIssueRow(issue, fileKey, figmaToken)).join("\n")}
            </div>
          </div>`;
}

export function renderIssueRow(
  issue: AnalysisIssue,
  fileKey: string,
  figmaToken?: string
): string {
  const sev = issue.config.severity;
  const def = issue.rule.definition;
  const link = buildFigmaDeepLink(fileKey, issue.violation.nodeId);

  return `              <details class="border border-border rounded-md overflow-hidden">
                <summary class="flex items-center gap-2.5 px-3 py-2 text-sm cursor-pointer hover:bg-muted/50 transition-colors">
                  <span class="w-1.5 h-1.5 rounded-full ${severityDot(sev)} shrink-0"></span>
                  <span class="font-medium shrink-0">${esc(def.name)}</span>
                  <span class="text-muted-foreground truncate text-xs flex-1">${esc(issue.violation.message)}</span>
                  <span class="inline-flex items-center px-1.5 py-0.5 text-[10px] font-medium rounded border ${severityBadge(sev)} shrink-0">${issue.calculatedScore}</span>
                </summary>
                <div class="px-3 py-3 bg-muted/30 border-t border-border text-sm space-y-2">
                  <div class="font-mono text-xs text-muted-foreground break-all">${esc(issue.violation.nodePath)}</div>
                  <div class="text-muted-foreground leading-relaxed space-y-1">
                    <p><span class="font-medium text-foreground">Why:</span> ${esc(def.why)}</p>
                    <p><span class="font-medium text-foreground">Impact:</span> ${esc(def.impact)}</p>
                    <p><span class="font-medium text-foreground">Fix:</span> ${esc(def.fix)}</p>
                  </div>
                  <div class="flex items-center gap-2 mt-1 no-print">
                    <a href="${link}" target="_blank" rel="noopener" class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium border border-border rounded-md hover:bg-muted transition-colors">Open in Figma <span>→</span></a>${figmaToken ? `
                    <button onclick="postComment(this)" data-file-key="${esc(fileKey)}" data-node-id="${esc(issue.violation.nodeId)}" data-message="${esc(issue.violation.message)}" class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium border border-border rounded-md hover:bg-muted transition-colors cursor-pointer">Comment on Figma</button>` : ""}
                  </div>
                </div>
              </details>`;
}

// ---- Utils ----

function getQuickWins(issues: AnalysisIssue[], limit: number): AnalysisIssue[] {
  return issues
    .filter(issue => issue.config.severity === "blocking")
    .sort((a, b) => a.calculatedScore - b.calculatedScore)
    .slice(0, limit);
}

function groupIssuesByCategory(issues: AnalysisIssue[]): Map<Category, AnalysisIssue[]> {
  const grouped = new Map<Category, AnalysisIssue[]>();
  for (const category of CATEGORIES) grouped.set(category, []);
  for (const issue of issues) grouped.get(issue.rule.definition.category)!.push(issue);
  return grouped;
}

const esc = escapeHtml;
